# Generated by Django 6.0 on 2025-12-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.stream'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.stream'),
        ),
    ]
