# Generated by Django 6.0 on 2025-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_studentprofile_stream_teacherprofile_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank='True', null='True'),
        ),
    ]
