# Generated by Django 6.0 on 2025-12-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick')], max_length=10),
        ),
    ]
