# Generated by Django 6.0 on 2025-12-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
