# Generated by Django 6.0 on 2025-12-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
