# Generated by Django 6.0 on 2026-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
    ]
