# Generated by Django 6.0 on 2026-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0010_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='My School', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='stream',
        ),
    ]
