# Generated by Django 6.0 on 2026-01-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0012_teacherprofile_classroom_teacherprofile_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SchoolSettings',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
