# Generated by Django 6.0 on 2026-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0013_remove_adminprofile_user_delete_schoolsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
            ],
        ),
    ]
