# Generated by Django 6.0 on 2026-01-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0014_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year_start',
            field=models.IntegerField(unique=True),
        ),
    ]
