# Generated by Django 6.0 on 2026-01-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0016_academicyear_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance_app.academicyear'),
        ),
    ]
