# Generated by Django 6.0 on 2026-01-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0017_alter_classroom_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='attendance_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='attendance_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='attendance_app.parentprofile'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='attendance_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='attendance_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.classroom'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.classroom'),
        ),
    ]
