# Generated by Django 6.0 on 2026-01-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0018_alter_attendance_student_alter_classroom_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance_app.classroom'),
        ),
    ]
