# Generated by Django 4.2.11 on 2026-02-05 02:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0021_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='school_logo'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='teacher_profile'),
        ),
    ]
