# Generated by Django 5.2.5 on 2026-03-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0025_alter_adminprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
