# Generated by Django 5.2.5 on 2026-03-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0026_remove_teacherprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick')], max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance_app.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance_app.classroom')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.teacherprofile')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_app.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date', 'classroom', 'stream', 'academic_year')},
            },
        ),
    ]
