# Generated by Django 5.2.5 on 2026-03-26 11:03

import attendance_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0028_alter_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Promoted', 'Promoted'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[attendance_app.models.validate_phone_number]),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='parentprofile',
            unique_together={('user', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('name', 'classroom')},
        ),
    ]
