# Generated by Django 5.2.5 on 2026-03-26 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0029_alter_parentprofile_user_alter_smslog_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Promoted', 'Promoted'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=15)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classattendancehistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classattendancehistory',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='classattendancehistory',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classattendancehistory',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='classattendancehistory',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='classattendancehistory',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parentprofile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_app.academicyear'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_app.classroom'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_app.stream'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.parentprofile'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_c37125_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['academic_year'], name='attendance__academi_3c3506_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status'], name='attendance__status_e8e40c_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_06f20e_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'academic_year'), name='unique_attendance_per_day_per_year'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_class_per_year'),
        ),
        migrations.AddConstraint(
            model_name='parentprofile',
            constraint=models.UniqueConstraint(fields=('user', 'student'), name='unique_parent_student'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('name', 'classroom'), name='unique_stream_per_class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_app.academicyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_app.classroom'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.stream'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance_app.studentprofile'),
        ),
        migrations.DeleteModel(
            name='ClassAttendanceHistory',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='stream',
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year'], name='attendance__academi_4b908e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='attendance__student_98348c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='attendance__status_ba19fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_per_year'),
        ),
    ]
