# Generated by Django 5.2.5 on 2026-04-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0030_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_day_per_year',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__academi_3c3506_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='stream',
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance_app.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_enrollments', to='attendance_app.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance_app.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'enrollment'), name='unique_attendance_per_day'),
        ),
    ]
