# Generated by Django 5.2.5 on 2026-04-04 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0031_remove_attendance_unique_attendance_per_day_per_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_enrollments', to='attendance_app.stream'),
        ),
    ]
