# Generated by Django 5.2.5 on 2026-04-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0032_alter_enrollment_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='attendance_app.classroom'),
        ),
    ]
