# Generated by Django 5.2.5 on 2026-04-18 10:24

import attendance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0033_alter_enrollment_classroom'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year_start',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick', 'Sick')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[attendance_app.models.validate_phone_number]),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_b7cbf3_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['-year_start'], name='attendance__year_st_217430_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_48d182_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='attendance__student_1d2b08_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment'], name='attendance__enrollm_7d4b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['marked_by'], name='attendance__marked__5df99f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_f5c2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_af706b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date'], name='attendance__enrollm_a8afe7_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['year'], name='attendance__year_id_032fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['name'], name='attendance__name_ee299a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['classroom'], name='attendance__classro_6ee479_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_teacher'], name='attendance__class_t_769952_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year', 'status'], name='attendance__academi_b42152_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['classroom', 'academic_year'], name='attendance__classro_88c5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_teacher', 'academic_year'], name='attendance__class_t_223aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['student'], name='attendance__student_6aed24_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['user'], name='attendance__user_id_3d4337_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolsettings',
            index=models.Index(fields=['school_name'], name='attendance__school__498291_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['student'], name='attendance__student_f50f77_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['parent'], name='attendance__parent__3e1e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['-timestamp'], name='attendance__timesta_6b3682_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['classroom'], name='attendance__classro_a93589_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['name'], name='attendance__name_c7dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['admission_number'], name='attendance__admissi_905129_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['user'], name='attendance__user_id_e67daf_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['user'], name='attendance__user_id_00db80_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='attendance__role_15cfcf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='attendance__usernam_fd28fc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='attendance__date_jo_c56f37_idx'),
        ),
    ]
