# Generated by Django 5.2.5 on 2026-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0034_alter_user_options_alter_academicyear_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('class_teacher__isnull', False)), fields=('class_teacher', 'academic_year', 'classroom', 'stream'), name='unique_teacher_per_class_stream_per_year'),
        ),
    ]
