# Generated by Django 5.2.5 on 2026-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0035_enrollment_unique_teacher_per_class_stream_per_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(choices=[('Form I', 'Form I'), ('Form II', 'Form II'), ('Form III', 'Form III'), ('Form IV', 'Form IV'), ('Form V', 'Form V'), ('Form VI', 'Form VI')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], db_index=True, max_length=5),
        ),
    ]
