# Generated by Django 5.2.5 on 2026-05-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0036_alter_classroom_options_alter_stream_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parentprofile',
            name='unique_parent_student',
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='parentprofile',
            constraint=models.UniqueConstraint(fields=('user', 'student'), name='unique_parent_student_pair'),
        ),
    ]
